### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [offMomySon/spring_reservation_project#27]
Hi,<br><br>url : https://github.com/offMomySon/spring_reservation_project/blob/7eb5be05988ad291964c5a1feed47c07aa0ebd47/src/main/resources/application.yml <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by offMomySon** [comment]
haha.. it just dummy server.
but thank you, next time i will remove that
